openapi: 3.0.0
info:
  title: parrot
  version: 1.0.0
servers:
  - url: 'http://localhost:8100'
    description: Local

paths:
  /api/ping:
    get:
      tags:
        - Health Check
      summary: Ping service
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
                example: pong
  /api/chords:
    get:
      tags:
        - Chords
      summary: Get Chords
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - Chords
      summary: Create Chord
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Real Madrid Fans
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}

  /api/chords/{id}:
    get:
      tags:
        - Chords
      summary: Get Chord by Id
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Chord Id
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  
  /api/messages:
    get:
      tags:
        - Messages
      summary: Get Messages
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: chordId
          schema:
            type: string
          description: Chord Id
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - Messages
      summary: Create Message
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Real Madrid Fans
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}

  /api/messages/{id}:
    get:
      tags:
        - Messages
      summary: Get Message by Id
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Message Id
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  
  /api/invite/circle:
    post:
      tags:
        - Invite
      summary: Get invite for creating new cicle
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Enter your bearer token
